#Azure Service Bus
svcbus:
  queue:
    name: events
  connectionString: $ServiceBusEndPoint
#KEDA
keda:
  queueLength: 5
  pollingInterval: 10 # seconds
  cooldownPeriod: 300 # seconds
  minReplicaCount: 0
  maxReplicaCount: 20
#APP
consumer:
  name: "consumer1"
  route: "/subscription"
producer:
  name: "producer1"
