apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: plant-tree-pubsub
spec:
  type: pubsub.azure.servicebus.queues
  version: v1
  metadata:
  # Required when not using Microsoft Entra ID Authentication
  - name: connectionString
    value: {{ .Values.svcbus.connectionString }}

scopes:
  - {{ .Values.consumer.name }}
  - {{ .Values.producer.name }}