apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: azsbus-dapr-retry-policy
spec:
  policies:
    retries:
       pubsubRetry:
        policy: exponential         
        maxInterval: 10s
        maxRetries: 5
  targets:
    components:
      plant-tree-pubsub:
        inbound:
          retry: pubsubRetry
scopes:
   - {{ .Values.consumer.name }}