apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: azsbus-dapr-sub-consumer1
spec:
  pubsubname: plant-tree-pubsub
  topic: {{ .Values.svcbus.queue.name }}
  routes:
    default: {{ .Values.consumer.route }}  
scopes:
  - {{ .Values.consumer.name }}