#APP
podAnnotations:    
  dapr.io/enabled: "true"
  dapr.io/app-protocol: "http"  
  dapr.io/log-as-json: "true"
  dapr.io/log-level: "debug"
  dapr.io/enable-api-logging: "true"
consumer:
  name: "consumer1"
  port: 8080
  image:
    name: "consumer-app"    
    tag: "1.0.0"
producer:
  name: "producer1"
  port: 8081
  image:
    name: "producer-app"    
    tag: "1.0.0"
#IMAGE
image:
  repository: "acrdev001br.azurecr.io"    
  pullPolicy: "Always"
#KEDA
keda:
  queueName: "consumer1-events"
  queueLength: 5
  pollingInterval: 10 
  cooldownPeriod: 300 
  minReplicaCount: 0 
  maxReplicaCount: 20 
rabbitmq:
  topic:    
    name: events        
  queue:    
    type: quorum       