apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: plant-tree-pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    value: "amqp://guest:guest@rabbitmqcluster.myns.svc:5672"
  - name: durable
    value: true
  - name: deletedWhenUnused
    value: false
  - name: autoAck
    value: false
  - name: deliveryMode
    value: 2
  - name: prefetchCount
    value: 1
  - name: reconnectWait
    value: 0
  - name: concurrencyMode
    value: parallel
  - name: publisherConfirm
    value: false
  - name: exchangeKind
    value: topic
