#RBMQ
rabbitmq:
  cluster:
    name: rabbitmq-cluster
  exchange:
    type: topic
    name: events
    autoDelete: false
    durable: true
  queue:
    name: consumer1-events
    type: quorum
    autoDelete: false
    durable: true  
  user:
    name: "guest"
    password: "guest"
#KEDA
keda:  
  queueLength: 5
  pollingInterval: 10 
  cooldownPeriod: 300 
  minReplicaCount: 0 
  maxReplicaCount: 20
#APP
consumer:
  name: "consumer1"
  route: "/subscription"