---
apiVersion: v1
kind: Secret
metadata:
  name: rbmq-guest-user-credentials
type: Opaque
stringData:
  username: {{ .Values.rabbitmq.user.name }}
  password: {{ .Values.rabbitmq.user.password }}
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rbmq-guest-user
spec:
  rabbitmqClusterReference:
    name: {{ .Values.rabbitmq.cluster.name }}
  importCredentialsSecret:
    name: rbmq-guest-user-credentials
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rbmq-guest-user-permission
spec:
  vhost: "/"
  user: {{ .Values.rabbitmq.user.name }}
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: {{ .Values.rabbitmq.cluster.name }}