apiVersion: v1
kind: Secret
metadata:
  name: rbmq-host-secrets
type: Opaque
stringData:
  host: "amqp://{{ .Values.rabbitmq.user.name }}:{{ .Values.rabbitmq.user.password }}@{{ .Values.rabbitmq.cluster.name }}.{{ .Release.Namespace }}.svc:5672"
  userPassword: {{ .Values.rabbitmq.user.password }}