apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: rbmq-dapr-sub-consumer1
spec:
  pubsubname: rbmq-dapr-pubsub
  topic: {{ .Values.rabbitmq.exchange.name }}
  routes:
    default: {{ .Values.consumer.route }}
  deadLetterTopic: {{ .Values.rabbitmq.exchange.name }}-dlq
  metadata:
    queueType: {{ .Values.rabbitmq.queue.type }}
scopes:
  - {{ .Values.consumer.name }}