apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: consumer-dapr-retry
spec:
  policies:
    retries:
       pubsubRetry:
        policy: exponential         
        maxInterval: 10s
        maxRetries: 5
  targets:
    components:
      pubsub001:
        inbound:
          retry: pubsubRetry
scopes:
   - consumer1