apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
data:
  host: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xY2x1c3Rlci5teW5zLnN2Yzo1Njcy
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth
spec:
  secretTargetRef:
    - parameter: host
      name: keda-rabbitmq-secret
      key: host
---      
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-scaler-consumer
spec:
  scaleTargetRef:
    name: consumer1
  pollingInterval: 10
  cooldownPeriod: 300
  minReplicaCount: 0
  maxReplicaCount: 20
  triggers:
    - type: rabbitmq
      metadata:
        queueName: consumer1-events
        queueLength: "5"
      authenticationRef:
        name: keda-trigger-auth