apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: az-svcbus-dapr-pubsub
spec:
  type: pubsub.azure.servicebus.topics
  version: v1
  metadata:  
  - name: connectionString
    value: __UPDATE_ME__
  