apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub001
spec:
  type: pubsub.azure.servicebus.topics
  version: v1
  metadata:
  # Required when not using Microsoft Entra ID Authentication
  - name: connectionString
    value: { service_bus_endpoint }
  