apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: redis-dapr-sub-consumer1
spec:
  pubsubname: plant-tree-pubsub
  topic: {{ .Values.redis.list.name }}
  routes:
    default: {{ .Values.consumer.route }}
  deadLetterTopic: {{ .Values.redis.list.name }}-dlx  
scopes:
  - {{ .Values.consumer.name }}