apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis-dapr-pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: {{ .Values.redis.address }}
  - name: redisPassword
    value: {{ .Values.redis.user.password }}