apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-keda-scaler-consumer  
spec:
  scaleTargetRef:
    name: {{ .Values.consumer.name }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  triggers:
  - type: redis
    metadata:
      address: {{ .Values.redis.address }}
      listName: {{ .Values.redis.list.name }}
      listLength: {{ .Values.keda.listLength }}
    authenticationRef:
      name: redis-keda-auth
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: redis-keda-auth
spec:
  secretTargetRef:
  - parameter: username
    name: redis-keda-secret
    key: redis_username
  - parameter: password
    name: redis-keda-secret
    key: redis_password
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-keda-secret
  namespace: my-project
type: Opaque
data:
  redis_username:  {{ .Values.redis.user.name }}
  redis_password:  {{ .Values.redis.user.password }}